In [2]:
import numpy as np

a = np.random.randn(32,32,3)
print (a.size)

3072


In [3]:
b = np.random.randn(4,3)
c = np.random.randn(3,2)
print ((b*c).shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [10]:
print (np.linalg.norm(b, axis=1, keepdims=True))
print(b)

[[ 1.44367992]
 [ 3.23233428]
 [ 0.58523466]
 [ 1.18834817]]
[[ 0.389051    0.95810103 -1.00741921]
 [ 1.69561201  2.63140921 -0.80533868]
 [-0.24852119  0.20480535  0.48866307]
 [-1.00252679  0.6145256   0.17166736]]
